# @format

services:
    - type: web
      name: auth-app
      env: docker
      region: oregon
      plan: free
      dockerfilePath: ./Dockerfile
      envVars:
          - key: NODE_ENV
            value: production
          - key: DATABASE_URL
            value: YOUR_DATABASE_URL_HERE
          - key: RESEND_API_KEY
            value: YOUR_RESEND_API_KEY_HERE
          - key: JWT_SECRET
            value: YOUR_JWT_SECRET
